name: flutter_js_polyfill
description: Flutter polyfills for dart:js APIs
version: 2.0.1
homepage: https://github.com/apptreesoftware/flutter_js_polyfill
author: John Ryan <john.p.ryan4@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0
